<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="preview-system" aria-labelledby="preview-title">
      <div class="container proof-grid"><div class="proof-copy"><div class="section-kicker">Preview Before Purchase</div><h2 id="preview-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '报告预览系统' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '每份报告都应有公开落地页，提供足够信息证明价值，同时不泄露完整产品。' ) ) ); ?></p></div><div class="proof-panel"><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['included_item'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul></div></div>
    </section>
