<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="video-library-hero"><div class="container"><p class="eyebrow"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'eyebrow', $block ?? null, 'Robert Khoubian Market Intelligence' ) ) ); ?></p><h1><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '国际贸易市场情报视频简报' ) ) ); ?></h1><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '通过 Robert Khoubian 经批准的数字分身和声音克隆，以4–5分钟解释报告、海关数据方法和市场准入分析。' ) ) ); ?></p><div class="hero-actions"><a class="btn btn-primary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'latest_briefing_link', $block ?? null, array( 'url' => '#latest-video', 'title' => '最新简报', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'latest_briefing_link', $block ?? null, array( 'url' => '#latest-video', 'title' => '最新简报', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary youtube-link" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'youtube_channel_link', $block ?? null, array( 'url' => '#', 'title' => '访问 YouTube 频道', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>" aria-disabled="true" data-cms-field="youtube_channel_url"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'youtube_channel_link', $block ?? null, array( 'url' => '#', 'title' => '访问 YouTube 频道', 'target' => '' ) ) ) ); ?></a></div></div></section>
