<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="catalog" aria-labelledby="catalog-title">
      <div class="container"><div class="section-head"><div><div class="section-kicker">Initial Catalog</div><h2 id="catalog-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Report products prepared for CMS upload.' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'These are the first product categories for the store. Each item is designed so you can later upload a cover, executive summary, sample PDF, protected paid PDF, price, license and translations from the admin panel.' ) ) ); ?></p></div></div><div class="reports-grid"><?php foreach ( \Qwerty\Soft\Support\DesignListing::rows( \Qwerty\Soft\Support\DesignField::value( 'source', $block ?? null ), (int) \Qwerty\Soft\Support\DesignField::value( 'limit', $block ?? null ), array( 'cover_kicker' => 'text', 'cover_title' => 'text', 'cover_subtitle' => 'text', 'report_type' => 'text', 'availability_status' => 'text', 'report_title' => 'text', 'report_summary' => 'textarea', 'include_1_mark' => 'text', 'include_1' => 'text', 'include_2_mark' => 'text', 'include_2' => 'text', 'include_3_mark' => 'text', 'include_3' => 'text', 'include_4_mark' => 'text', 'include_4' => 'text', 'badge_1' => 'text', 'badge_2' => 'text', 'badge_3' => 'text', 'price_note' => 'text', 'price' => 'text', 'preview_link' => 'link', 'buy_link' => 'link' ), 'qs_report' ) as $qsoft_row ) : ?><article class="report-card" data-category="china">
      <div class="report-cover cover-china">
        <span><?php echo esc_html( (string) ( $qsoft_row['cover_kicker'] ?? '' ) ); ?></span>
        <strong><?php echo esc_html( (string) ( $qsoft_row['cover_title'] ?? '' ) ); ?></strong>
        <small><?php echo esc_html( (string) ( $qsoft_row['cover_subtitle'] ?? '' ) ); ?></small>
      </div>
      <div class="report-body">
        <div class="report-meta"><span><?php echo esc_html( (string) ( $qsoft_row['report_type'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['availability_status'] ?? '' ) ); ?></span></div>
        <h3><?php echo esc_html( (string) ( $qsoft_row['report_title'] ?? '' ) ); ?></h3>
        <p><?php echo esc_html( (string) ( $qsoft_row['report_summary'] ?? '' ) ); ?></p>
        <ul class="report-includes"><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['include_1_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['include_1'] ?? '' ) ); ?></span></li><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['include_2_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['include_2'] ?? '' ) ); ?></span></li><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['include_3_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['include_3'] ?? '' ) ); ?></span></li><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['include_4_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['include_4'] ?? '' ) ); ?></span></li></ul>
        <div class="report-badges"><span><?php echo esc_html( (string) ( $qsoft_row['badge_1'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['badge_2'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['badge_3'] ?? '' ) ); ?></span></div>
        <div class="report-price"><span><?php echo esc_html( (string) ( $qsoft_row['price_note'] ?? '' ) ); ?></span><strong><?php echo esc_html( (string) ( $qsoft_row['price'] ?? '' ) ); ?></strong></div>
        <div class="report-actions"><a class="btn btn-outline" href="<?php echo \Qwerty\Soft\Support\DesignField::url( $qsoft_row['preview_link'] ?? '' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( $qsoft_row['preview_link'] ?? '' ) ); ?></a><a class="btn btn-primary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( $qsoft_row['buy_link'] ?? '' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( $qsoft_row['buy_link'] ?? '' ) ); ?></a></div>
      </div>
    </article><?php endforeach; ?>




</div></div>
    </section>
