<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="latest-video"><div class="container video-intelligence-grid"><div class="video-player-card"><span class="video-duration"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'video_duration', $block ?? null, '4:30' ) ) ); ?></span><span class="video-play"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'play_symbol', $block ?? null, '▶' ) ) ); ?></span><div class="video-player-copy"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'eyebrow', $block ?? null, 'Latest briefing' ) ) ); ?></span><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'How to Read a Customs-Based Market Report' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'summary', $block ?? null, 'A concise explanation of HS-code scope, data coverage, ranking limitations and the commercial meaning behind the numbers.' ) ) ); ?></p></div></div><aside class="video-learn-card"><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'learning_points_heading', $block ?? null, 'What you will learn' ) ) ); ?></h3><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><?php echo esc_html( (string) ( $qsoft_row['learning_point'] ?? '' ) ); ?></li><?php endforeach; ?></ul><p class="video-disclosure"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'disclosure', $block ?? null, 'AI-assisted presentation using Robert Khoubian’s approved digital avatar and voice clone. Script, analysis and final publication are reviewed and approved by Robert Khoubian.' ) ) ); ?></p></aside></div></section>
