<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="latest-video"><div class="container video-intelligence-grid"><div class="video-player-card"><span class="video-duration"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'video_duration', $block ?? null, '4:30' ) ) ); ?></span><span class="video-play"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'play_icon', $block ?? null, '▶' ) ) ); ?></span><div class="video-player-copy"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'eyebrow', $block ?? null, 'Последний брифинг' ) ) ); ?></span><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'video_title', $block ?? null, 'Как правильно читать отчет на основе таможенных данных' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'video_summary', $block ?? null, 'Краткое объяснение HS-кодов, охвата данных, ограничений рейтингов и коммерческого смысла показателей.' ) ) ); ?></p></div></div><aside class="video-learn-card"><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'takeaways_heading', $block ?? null, 'Что вы узнаете' ) ) ); ?></h3><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><?php echo esc_html( (string) ( $qsoft_row['takeaway'] ?? '' ) ); ?></li><?php endforeach; ?></ul><p class="video-disclosure"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'ai_disclosure', $block ?? null, 'AI-assisted презентация с утвержденным цифровым аватаром и клоном голоса Роберта Хубияна. Сценарий, анализ и публикация проверяются и утверждаются Робертом Хубияном.' ) ) ); ?></p></aside></div></section>
