<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="programs" aria-labelledby="programs-title">
      <div class="container">
        <div class="section-head"><div><div class="section-kicker">研究项目</div><h2 id="programs-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '正在建立的旗舰研究项目' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '这些项目将成为平台的长期编辑主线。初期可以以文章形式发布，随后发展为付费报告、季度展望和年度出版物。' ) ) ); ?></p></div></div>
        <div class="project-grid research-program-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="project-card"><h3><?php echo esc_html( (string) ( $qsoft_row['program_name'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['program_description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div>
      </div>
    </section>
