<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="media-strip" aria-labelledby="media-title"><div class="container media-strip-grid"><div><div class="section-kicker light">媒体与研究咨询</div><h2 id="media-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '面向媒体、会议组织者和行业合作伙伴。' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'description', $block ?? null, 'Robert Khoubian 可就全球食品贸易、中国供应链、俄罗斯和独联体市场准入、冷冻食品物流、监管要求和跨境贸易风险提供观点。' ) ) ); ?></p></div><div class="media-actions"><a class="btn btn-primary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'contact_link', $block ?? null, array( 'url' => 'mailto:robert@robertkhoubian.com', 'title' => '联系', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'contact_link', $block ?? null, array( 'url' => 'mailto:robert@robertkhoubian.com', 'title' => '联系', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'reports_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13606', 'title' => '查看报告', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'reports_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13606', 'title' => '查看报告', 'target' => '' ) ) ) ); ?></a></div></div></section>
