<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="methodology"><div class="container"><div class="report-callout"><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Методология и публикационные права' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'note', $block ?? null, 'Исходный отчет использует исторические и прогнозные данные и ссылается на Euromonitor International, Mintel GNPD и Global Trade Tracker. Перед публичной публикацией полной версии или платного отчета нужно подтвердить права на использование детальных third-party tables. Текущая страница — краткая website-ready версия, а не полное воспроизведение исходного документа.' ) ) ); ?></p></div></div></section>
