<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="discipline" aria-labelledby="discipline-title">
      <div class="container"><div class="method-note"><div class="section-kicker">Evidence &amp; Compliance</div><h2 id="discipline-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Publishing discipline' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'body', $block ?? null, 'High-value claims, rankings, retail reach, memberships and government-linked participation should remain tied to the internal evidence register before they appear in paid reports, media outreach or Wikipedia-related materials.' ) ) ); ?></p></div></div>
    </section>
