<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="framework"><div class="container"><div class="section-head"><div><div class="section-kicker">Index Framework</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'What the index measures' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'Each published score is built from documented inputs, standardized sub-scores and a dated methodology note. Weightings may vary by index family, but any published result must disclose the applicable version and source period.' ) ) ); ?></p></div></div><div class="index-dimensions"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="index-dimension"><div class="index-dimension-head"><h3><?php echo esc_html( (string) ( $qsoft_row['dimension'] ?? '' ) ); ?></h3><span><?php echo esc_html( (string) ( $qsoft_row['weighting'] ?? '' ) ); ?></span></div><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div></div></section>
