<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section newsletter" id="newsletter" aria-labelledby="newsletter-title"><div class="container"><div class="newsletter-card"><div><h2 id="newsletter-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Receive the Weekly China–Eurasia Food Trade Briefing' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'One concise email covering customs data, market access, frozen food trade and the indicators that matter to operators.' ) ) ); ?></p></div><form class="signup"><input type="email" placeholder="Business email address" aria-label="Business email address"><button class="btn btn-primary" type="button">Subscribe to the Briefing</button></form></div></div></section>
