<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="methodology" aria-labelledby="methodology-title">
      <div class="container proof-grid">
        <div class="proof-copy"><div class="section-kicker">Методология</div><h2 id="methodology-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Аналитика, основанная на операционном опыте' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'Платформа должна строиться на дисциплинированной методологии: практическое знание рынков, официальные или надежные данные там, где они доступны, мониторинг требований, документированный опыт и четкое разделение фактов и мнений. Коммерчески чувствительные утверждения остаются в evidence register до подготовки подтверждений.' ) ) ); ?></p></div>
        <div class="proof-panel methodology-panel"><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['principle'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul></div>
      </div>
    </section>
