<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="page-hero research-hero" aria-labelledby="research-title">
      <div class="container page-hero-grid">
        <div>
          <p class="eyebrow"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'eyebrow', $block ?? null, '研究与市场情报' ) ) ); ?></p>
          <h1 id="research-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '为实际贸易决策服务的食品贸易情报。' ) ) ); ?></h1>
          <p class="lead"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lead', $block ?? null, '专注于中国食品出口、中国—欧亚贸易通道、冷冻食品供应链、市场准入、监管要求和贸易风险的专业研究中心。' ) ) ); ?></p>
          <div class="hero-actions"><a class="btn btn-primary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'primary_link', $block ?? null, array( 'url' => '#intelligence', 'title' => '查看情报', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'primary_link', $block ?? null, array( 'url' => '#intelligence', 'title' => '查看情报', 'target' => '' ) ) ) ); ?></a><a class="btn btn-outline" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'secondary_link', $block ?? null, array( 'url' => '#methodology', 'title' => '研究方法', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'secondary_link', $block ?? null, array( 'url' => '#methodology', 'title' => '研究方法', 'target' => '' ) ) ) ); ?></a></div>
        </div>
        <aside class="research-panel" aria-label="Research focus summary">
          <div class="research-panel-head"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'panel_heading', $block ?? null, '研究重点' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'panel_scope', $block ?? null, '中国 • 欧亚 • 冷冻食品' ) ) ); ?></strong></div>
          <ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['focus_point'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul>
        </aside>
      </div>
    </section>
