<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="methodology"><div class="container"><div class="report-callout"><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Methodology and publishing note' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'note', $block ?? null, 'The source report uses forecast and historical data and references Euromonitor International, Mintel GNPD and Global Trade Tracker. Before this page is made public as a paid or downloadable report, publishing rights for detailed third-party tables should be confirmed. The current page is a website-ready summary and should not be treated as a full reproduction of the source document.' ) ) ); ?></p></div></div></section>
