<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="profile" aria-labelledby="profile-title">
      <div class="container media-layout">
        <div class="content-block feature-block">
          <div class="section-kicker">媒体简介</div>
          <h2 id="profile-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Robert Khoubian 是谁？' ) ) ); ?></h2>
          <div class="two-col media-bio">
            <article><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'short_bio_heading', $block ?? null, '简短简介' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'short_bio', $block ?? null, 'Robert Khoubian 是国际食品贸易专业人士、企业家和市场情报发布者，专注于中国—欧亚食品贸易、冷冻食品供应链和跨境市场准入。自 2004 年以来，他的工作覆盖中国、俄罗斯及独联体市场、北美、东南亚和欧盟。' ) ) ); ?></p></article>
            <article><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'detailed_bio_heading', $block ?? null, '详细简介' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'detailed_bio', $block ?? null, 'Robert 的工作结合了商业执行、监管知识和实用市场情报。他的经验包括国际食品贸易、海关和兽医要求、加拿大政府贸易代表团、零售产品本地化、冷链物流，以及 Aquaprole Group 在加拿大、美国、新加坡、中国和香港的发展。' ) ) ); ?></p></article>
          </div>
        </div>
        <aside class="content-block quick-panel">
          <h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'formats_heading', $block ?? null, '适合的形式' ) ) ); ?></h3>
          <div class="country-chips media-chips"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><span><?php echo esc_html( (string) ( $qsoft_row['format'] ?? '' ) ); ?></span><?php endforeach; ?></div>
        </aside>
      </div>
    </section>
