<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft report-video-briefing"><div class="container report-video-grid"><div><div class="section-kicker">市场情报视频简报</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '观看本报告的视频简报' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, '用4–5分钟AI辅助视频说明报告的核心结论、方法、局限及商业含义。' ) ) ); ?></p><a class="btn btn-outline" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'video_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13611', 'title' => '打开视频简报', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'video_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13611', 'title' => '打开视频简报', 'target' => '' ) ) ) ); ?></a></div><div class="video-player-card"><span class="video-duration"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'duration', $block ?? null, '4:30' ) ) ); ?></span><span class="video-play"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'play_symbol', $block ?? null, '▶' ) ) ); ?></span><div class="video-player-copy"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'video_kicker', $block ?? null, '精选报告视频简报' ) ) ); ?></span><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'video_title', $block ?? null, '如何阅读一份基于海关数据的市场报告' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'video_description', $block ?? null, '简明说明HS编码、数据覆盖、排名限制以及数字背后的商业含义。' ) ) ); ?></p></div></div></div></section>
