<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="programs" aria-labelledby="programs-title">
      <div class="container">
        <div class="section-head"><div><div class="section-kicker">Исследовательские программы</div><h2 id="programs-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Флагманские направления в разработке' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'Эти направления должны стать редакционной основой платформы. Сначала они могут выходить как статьи, затем перерасти в платные отчеты, квартальные обзоры и ежегодные публикации.' ) ) ); ?></p></div></div>
        <div class="project-grid research-program-grid"><?php foreach ( \Qwerty\Soft\Support\DesignListing::rows( \Qwerty\Soft\Support\DesignField::value( 'source', $block ?? null ), (int) \Qwerty\Soft\Support\DesignField::value( 'limit', $block ?? null ), array( 'program_name' => 'text', 'description' => 'textarea' ), '' ) as $qsoft_row ) : ?><article class="project-card"><h3><?php echo esc_html( (string) ( $qsoft_row['program_name'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div>
      </div>
    </section>
