<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="markets" aria-labelledby="markets-title">
      <div class="container footprint-grid">
        <div class="footprint-copy"><div class="section-kicker">Markets</div><h2 id="markets-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Research organized by trade corridor' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'The platform should be easy for international visitors to navigate by region, product and business question. The first priority is the China–Eurasia food trade corridor, supported by North American and Southeast Asian experience.' ) ) ); ?></p></div>
        <div class="map-card"><div class="region-list">
          <?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><div class="region-row"><strong><?php echo esc_html( (string) ( $qsoft_row['region'] ?? '' ) ); ?></strong><div class="country-chips"><span><?php echo esc_html( (string) ( $qsoft_row['first_country'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['second_country'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['third_country'] ?? '' ) ); ?></span></div></div><?php endforeach; ?>
        </div></div>
      </div>
    </section>
