<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section"><div class="container"><div class="section-head"><div><div class="section-kicker">Strategic Reading</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Коммерческая интерпретация для экспортеров.' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'Этот блок переводит исходный отчет в практическую логику market entry для oat exporters, брендов и пользователей рыночной аналитики.' ) ) ); ?></p></div></div><div class="insight-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="insight-card"><h3><?php echo esc_html( (string) ( $qsoft_row['market'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['assessment'] ?? '' ) ); ?></p></article><?php endforeach; ?></div></div></section>
