<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section"><div class="container scorecard-layout"><div><div class="section-kicker">Демонстрационная карточка</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Пример визуализации — не опубликованный рейтинг' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'Ниже показан только пример дизайна. Его нельзя цитировать как текущий рыночный вывод.' ) ) ); ?></p><div class="legal-note"><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'notice_heading', $block ?? null, 'Уведомление о названии и методологии' ) ) ); ?></strong><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'notice_text', $block ?? null, 'Robert Khoubian Market Intelligence Index™, RKMII™ и дизайн карточек представлены как заявленные обозначения бренда и авторской методологии. Символ ™ означает заявление о праве на обозначение и не подтверждает государственную регистрацию товарного знака.' ) ) ); ?></p></div></div><div class="scorecard-demo"><div class="scorecard-top"><div><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'total_score_label', $block ?? null, 'Демонстрационный итоговый балл' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'total_score', $block ?? null, '82' ) ) ); ?></strong></div><b><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'status', $block ?? null, 'СТАТУС: ТОЛЬКО ДЕМОНСТРАЦИЯ' ) ) ); ?></b></div></div></div></section>
