<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section"><div class="container scorecard-layout"><div><div class="section-kicker">Illustrative Scorecard</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Example presentation — not a published market ranking' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'The following score is a design demonstration only. It must not be cited as a current market conclusion.' ) ) ); ?></p><div class="legal-note"><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'notice_heading', $block ?? null, 'Name and methodology notice' ) ) ); ?></strong><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'notice_text', $block ?? null, 'Robert Khoubian Market Intelligence Index™, RKMII™ and associated scorecard designs are presented as proprietary brand and methodology identifiers. The ™ symbol indicates a claimed mark; it does not state that a trademark registration has been granted.' ) ) ); ?></p></div></div><div class="scorecard-demo"><div class="scorecard-top"><div><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'overall_score_label', $block ?? null, 'Illustrative overall score' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'overall_score', $block ?? null, '82' ) ) ); ?></strong></div><b><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'status_note', $block ?? null, 'STATUS: DEMONSTRATION ONLY' ) ) ); ?></b></div></div></div></section>
