<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="media-strip" id="contact" aria-labelledby="contact-title">
      <div class="container media-strip-grid">
        <div><div class="section-kicker light">Contact</div><h2 id="contact-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '媒体联系' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '如需采访、书面评论、会议圆桌、网络研讨会或专业咨询，可直接联系 Robert Khoubian。' ) ) ); ?></p><p class="media-small-note"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'note', $block ?? null, '该媒体页面旨在为未来的媒体沟通和行业合作提供清晰资料，同时保持保守、可验证的公开形象。' ) ) ); ?></p></div>
        <div class="media-actions"><a class="btn btn-light" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'email_link', $block ?? null, array( 'url' => 'mailto:robert@robertkhoubian.com', 'title' => '发送邮件', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'email_link', $block ?? null, array( 'url' => 'mailto:robert@robertkhoubian.com', 'title' => '发送邮件', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'about_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13603', 'title' => '关于', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'about_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13603', 'title' => '关于', 'target' => '' ) ) ) ); ?></a></div>
      </div>
    </section>
