<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section latest-intelligence" id="latest-intelligence" aria-labelledby="latest-title">
      <div class="container data-feature">
        <div class="data-feature-copy">
          <div class="section-kicker">Latest Intelligence</div>
          <h2 id="latest-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'China’s poultry exports to Russia accelerated in 2025.' ) ) ); ?></h2>
          <p class="data-lede"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'Volume growth materially outpaced value growth, pointing to lower average unit value and stronger price competition. For exporters, the strategic issue is not only market expansion, but margin discipline, approved-plant access and buyer concentration.' ) ) ); ?></p>
          <div class="source-line"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><span><?php echo esc_html( (string) ( $qsoft_row['label'] ?? '' ) ); ?></span><?php endforeach; ?></div>
          <a class="text-link strong-link" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'read_more', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13590', 'title' => 'Read the analysis →', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'read_more', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13590', 'title' => 'Read the analysis →', 'target' => '' ) ) ) ); ?></a>
        </div>
        <div class="metric-panel" aria-label="China poultry exports to Russia 2025 key metrics">
          <div class="metric-main"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'headline_metric_label', $block ?? null, '2025 export volume' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'headline_metric_value', $block ?? null, '114,662' ) ) ); ?></strong><small><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'headline_metric_unit', $block ?? null, 'metric tons' ) ) ); ?></small></div>
          <div class="metric-secondary"><div><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'growth_label', $block ?? null, 'YoY volume growth' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'growth_value', $block ?? null, '+55.3%' ) ) ); ?></strong></div><div><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'export_value_label', $block ?? null, 'Export value' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'export_value_amount', $block ?? null, 'US$170.65M' ) ) ); ?></strong></div></div>
          <div class="bar-compare" aria-label="2024 versus 2025 export volume"><div class="bar-row"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'baseline_year', $block ?? null, '2024' ) ) ); ?></span><i style="width:64%"></i><b><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'baseline_year_volume', $block ?? null, '73,832 MT' ) ) ); ?></b></div><div class="bar-row"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'comparison_year', $block ?? null, '2025' ) ) ); ?></span><i style="width:100%"></i><b><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'comparison_year_volume', $block ?? null, '114,662 MT' ) ) ); ?></b></div></div>
        </div>
      </div>
    </section>
