<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="markets" aria-labelledby="markets-title">
      <div class="container footprint-grid">
        <div class="footprint-copy"><div class="section-kicker">市场</div><h2 id="markets-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '按贸易通道组织研究' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '平台应便于国际访问者按地区、产品和商业问题查找信息。第一优先级是中国—欧亚食品贸易通道，并结合北美和东南亚经验。' ) ) ); ?></p></div>
        <div class="map-card"><div class="region-list">
          <?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><div class="region-row"><strong><?php echo esc_html( (string) ( $qsoft_row['region'] ?? '' ) ); ?></strong><div class="country-chips"><span><?php echo esc_html( (string) ( $qsoft_row['country_1'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['country_2'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['country_3'] ?? '' ) ); ?></span></div></div><?php endforeach; ?>
        </div></div>
      </div>
    </section>
