<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section newsletter" id="newsletter" aria-labelledby="newsletter-title"><div class="container"><div class="newsletter-card"><div><h2 id="newsletter-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '订阅 Global Food Trade Intelligence' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, '每周获取关于中国食品出口、冷冻食品市场、市场准入、贸易风险和国际供应链的洞察。' ) ) ); ?></p></div><form class="signup"><input type="email" placeholder="电子邮箱" aria-label="Email address"><button class="btn btn-primary" type="button">订阅情报</button></form></div></div></section>
