<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section dark"><div class="container"><p class="section-kicker"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'kicker', $block ?? null, '治理规则' ) ) ); ?></p><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '安全、声明控制与可信度' ) ) ); ?></h2><div class="grid four"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="card"><h3><?php echo esc_html( (string) ( $qsoft_row['rule'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div><p class="warning" style="margin-top:24px"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'disclaimer', $block ?? null, 'Robert AI 是 AI 辅助贸易智能系统，不应被视为法律、税务、海关、金融、兽医或制裁建议的替代品。如翻译内容不一致，应以已批准的原始材料为准。' ) ) ); ?></p></div></section>
