<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<header class="site-header" id="top">
    <div class="container nav-wrap">
      <a class="brand" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::site( 'site_header_df6ef7_brand', array( 'url' => 'http://localhost/winonweb-them/?page_id=13571', 'title' => 'RKRobert Khoubian', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>" aria-label="Robert Khoubian home"><span class="brand-mark">RK</span><span class="brand-text">Robert Khoubian</span></a>
      <button class="menu-toggle" aria-label="Open navigation" aria-controls="primary-nav" aria-expanded="false"><span></span><span></span><span></span></button>
      <nav class="primary-nav" id="primary-nav" aria-label="Primary navigation">
        <?php echo do_blocks( \Qwerty\Soft\Support\DesignField::menu() ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Rendered block markup. ?>
        
        
        
        
        
        
        <div class="language-switcher" aria-label="Language selection"><a class="lang-chip active" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::site( 'site_header_df6ef7_lang_chip', array( 'url' => '../en/', 'title' => 'EN', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>" lang="en"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::site( 'site_header_df6ef7_lang_chip', array( 'url' => '../en/', 'title' => 'EN', 'target' => '' ) ) ) ); ?></a><a class="lang-chip" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::site( 'site_header_df6ef7_lang_chip_2', array( 'url' => '../ru/', 'title' => 'RU', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>" lang="ru"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::site( 'site_header_df6ef7_lang_chip_2', array( 'url' => '../ru/', 'title' => 'RU', 'target' => '' ) ) ) ); ?></a><a class="lang-chip" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::site( 'site_header_df6ef7_lang_chip_3', array( 'url' => '../zh/', 'title' => '中文', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>" lang="zh-CN"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::site( 'site_header_df6ef7_lang_chip_3', array( 'url' => '../zh/', 'title' => '中文', 'target' => '' ) ) ) ); ?></a></div>
      </nav>
    </div>
  </header>
