<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section rkmii-home" aria-labelledby="rkmii-home-title"><div class="container rkmii-home-grid"><div><div class="section-kicker">Proprietary Methodology</div><h2 id="rkmii-home-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Robert Khoubian Market Intelligence Index™' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'description', $block ?? null, 'RKMII™ converts market size, growth, access, logistics, risk and competition into a structured decision framework. Numeric scores are published only when the required evidence inputs and methodology are complete.' ) ) ); ?></p><div class="section-actions"><a class="btn btn-outline" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'explore_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13578', 'title' => 'Explore RKMII™', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'explore_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13578', 'title' => 'Explore RKMII™', 'target' => '' ) ) ) ); ?></a></div></div><div class="rkmii-mini-score"><div class="score-tag">Framework preview</div><div class="score-bars"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><div><span><?php echo esc_html( (string) ( $qsoft_row['dimension'] ?? '' ) ); ?></span><i style="width:86%"></i></div><?php endforeach; ?></div><small><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'disclaimer', $block ?? null, 'Illustrative framework only. No public market score is implied.' ) ) ); ?></small></div></div></section>
