<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="page-hero research-hero" aria-labelledby="research-title">
      <div class="container page-hero-grid">
        <div>
          <p class="eyebrow"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'eyebrow', $block ?? null, 'Research & Market Intelligence' ) ) ); ?></p>
          <h1 id="research-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Food trade intelligence for practical decisions.' ) ) ); ?></h1>
          <p class="lead"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lead', $block ?? null, 'A professional research hub focused on China food exports, China–Eurasia trade corridors, frozen food supply chains, market access, regulatory requirements and trade risk.' ) ) ); ?></p>
          <div class="hero-actions"><a class="btn btn-primary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'primary_link', $block ?? null, array( 'url' => '#intelligence', 'title' => 'Explore Intelligence', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'primary_link', $block ?? null, array( 'url' => '#intelligence', 'title' => 'Explore Intelligence', 'target' => '' ) ) ) ); ?></a><a class="btn btn-outline" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'secondary_link', $block ?? null, array( 'url' => '#methodology', 'title' => 'Methodology', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'secondary_link', $block ?? null, array( 'url' => '#methodology', 'title' => 'Methodology', 'target' => '' ) ) ) ); ?></a></div>
        </div>
        <aside class="research-panel" aria-label="Research focus summary">
          <div class="research-panel-head"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'panel_heading', $block ?? null, 'Research Focus' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'panel_scope', $block ?? null, 'China • Eurasia • Frozen Food' ) ) ); ?></strong></div>
          <ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['focus_point'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul>
        </aside>
      </div>
    </section>
