<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="media-strip" id="contact" aria-labelledby="contact-title">
      <div class="container media-strip-grid">
        <div><div class="section-kicker light">Следующий шаг</div><h2 id="contact-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Сначала строим аудиторию, потом продаем отчеты.' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'description', $block ?? null, 'Первая цель — доверие: регулярно публиковать полезную аналитику, укреплять репутацию и затем превращать лучшие материалы в premium publications.' ) ) ); ?></p></div>
        <div class="media-actions"><a class="btn btn-light" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'primary_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13573#newsletter', 'title' => 'Подписаться', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'primary_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13573#newsletter', 'title' => 'Подписаться', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'secondary_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13595', 'title' => 'Медиа-центр', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'secondary_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13595', 'title' => 'Медиа-центр', 'target' => '' ) ) ) ); ?></a></div>
      </div>
    </section>
