<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="methodology"><div class="container"><div class="report-callout"><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '方法与发布说明' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'note', $block ?? null, '来源报告使用历史和预测数据，并引用 Euromonitor International、Mintel GNPD 和 Global Trade Tracker。在公开发布完整或付费版本之前，应确认详细第三方表格数据的使用权。本页面为网站版摘要，不是来源文件的完整复制。' ) ) ); ?></p></div></div></section>
