<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section"><div class="container report-detail-grid"><div class="proof-copy"><div class="section-kicker">Executive Summary</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '燕麦机会最集中的市场。' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, '来源报告显示，各市场的燕麦产品活动差异较大。墨西哥和巴西在所选市场中代理量和新品活动较高，日本是所选 APAC 市场中规模最大的一个。菲律宾和韩国规模较小，但在创新、功能性声称和加拿大产品存在方面具有参考价值。' ) ) ); ?></p></div><div class="proof-panel"><ul class="report-summary-list"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['finding'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul></div></div></section>
