<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="tools" aria-labelledby="tools-title">
      <div class="container">
        <div class="section-head"><div><div class="section-kicker">决策工具</div><h2 id="tools-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '下一步要建设的实用工具' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '这些工具将把专业经验转化为进口商、出口商、经纪人和贸易团队在报价、发货或进入市场前可以使用的资源。' ) ) ); ?></p></div></div>
        <div class="decision-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="project-card"><h3><?php echo esc_html( (string) ( $qsoft_row['tool_name'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div>
      </div>
    </section>
