<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section dark"><div class="container"><p class="section-kicker"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'kicker', $block ?? null, '使用场景' ) ) ); ?></p><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Robert AI 的四种模式' ) ) ); ?></h2><div class="grid four"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="card"><span class="pill"><?php echo esc_html( (string) ( $qsoft_row['mode_number'] ?? '' ) ); ?></span><h3><?php echo esc_html( (string) ( $qsoft_row['mode_name'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p><p><strong><?php echo esc_html( (string) ( $qsoft_row['availability_note'] ?? '' ) ); ?></strong></p></article><?php endforeach; ?></div></div></section>
