<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="intelligence" aria-labelledby="intelligence-title">
      <div class="container">
        <div class="section-head"><div><div class="section-kicker">情报范围</div><h2 id="intelligence-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '核心研究领域' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '本页面围绕实际贸易问题组织研究：什么产品可以出口、谁可以采购、需要哪些文件、存在什么风险，以及企业应如何构建商业决策。' ) ) ); ?></p></div></div>
        <div class="focus-grid research-focus-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="focus-card"><span><?php echo esc_html( (string) ( $qsoft_row['number'] ?? '' ) ); ?></span><h3><?php echo esc_html( (string) ( $qsoft_row['heading'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div>
      </div>
    </section>
