<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="media-strip" id="contact" aria-labelledby="contact-title">
      <div class="container media-strip-grid">
        <div><div class="section-kicker light">Contact</div><h2 id="contact-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Контакт для СМИ' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'Для интервью, письменных комментариев, панельных дискуссий, вебинаров или профессиональных запросов можно связаться с Робертом напрямую.' ) ) ); ?></p><p class="media-small-note"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'note', $block ?? null, 'Эта медиа-страница создана для будущей работы с прессой и отраслевыми организациями без чрезмерных или неподтвержденных заявлений.' ) ) ); ?></p></div>
        <div class="media-actions"><a class="btn btn-light" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'email_link', $block ?? null, array( 'url' => 'mailto:robert@robertkhoubian.com', 'title' => 'Написать Роберту', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'email_link', $block ?? null, array( 'url' => 'mailto:robert@robertkhoubian.com', 'title' => 'Написать Роберту', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'about_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13593', 'title' => 'О Роберте', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'about_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13593', 'title' => 'О Роберте', 'target' => '' ) ) ) ); ?></a></div>
      </div>
    </section>
