<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft proof" id="proof" aria-labelledby="proof-title"><div class="container proof-grid"><div class="proof-copy"><div class="section-kicker">Built on Real Trade Execution</div><h2 id="proof-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Research grounded in operating experience.' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'description', $block ?? null, 'Robert’s analysis is informed by more than two decades of international food-trade execution. Aquaprole Group provides practical exposure to sourcing, customs, market access, trade finance, cold-chain logistics, branded products and cross-border customer development.' ) ) ); ?></p><div class="section-actions"><a class="btn btn-outline" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'about_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13577', 'title' => 'About Robert', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'about_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13577', 'title' => 'About Robert', 'target' => '' ) ) ) ); ?></a></div></div><div class="proof-panel"><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['credential'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul></div></div></section>
