<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="profile" aria-labelledby="profile-title">
      <div class="container media-layout">
        <div class="content-block feature-block">
          <div class="section-kicker">Профиль для СМИ</div>
          <h2 id="profile-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Кто такой Роберт Хубиян?' ) ) ); ?></h2>
          <div class="two-col media-bio">
            <article><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'short_bio_heading', $block ?? null, 'Короткая биография' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'short_bio', $block ?? null, 'Роберт Хубиян — международный профессионал в торговле продуктами питания, предприниматель и издатель рыночной аналитики, специализирующийся на торговле между Китаем и Евразией, замороженных цепочках поставок и трансграничном рыночном доступе. С 2004 года он работает с рынками Китая, России и СНГ, Северной Америки, Юго-Восточной Азии и Европейского союза.' ) ) ); ?></p></article>
            <article><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'extended_bio_heading', $block ?? null, 'Расширенная биография' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'extended_bio', $block ?? null, 'Работа Роберта объединяет коммерческое исполнение, регуляторные знания и практическую рыночную аналитику. Его опыт включает международную торговлю продуктами питания, таможенные и ветеринарные требования, участие в канадских торговых миссиях, адаптацию продуктов для розничных каналов, холодную логистику и развитие Aquaprole Group в Канаде, США, Сингапуре, Китае и Гонконге.' ) ) ); ?></p></article>
          </div>
        </div>
        <aside class="content-block quick-panel">
          <h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'formats_heading', $block ?? null, 'Предпочтительные форматы' ) ) ); ?></h3>
          <div class="country-chips media-chips"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><span><?php echo esc_html( (string) ( $qsoft_row['format'] ?? '' ) ); ?></span><?php endforeach; ?></div>
        </aside>
      </div>
    </section>
