<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="stats-band proof-strip" aria-label="Verified credibility summary"><div class="container"><div class="stats-grid four"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="stat"><span><?php echo esc_html( (string) ( $qsoft_row['label'] ?? '' ) ); ?></span><strong><?php echo esc_html( (string) ( $qsoft_row['value'] ?? '' ) ); ?></strong><small><?php echo esc_html( (string) ( $qsoft_row['detail'] ?? '' ) ); ?></small></article><?php endforeach; ?></div></div></section>
