<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="media-strip" id="contact" aria-labelledby="contact-title">
      <div class="container media-strip-grid">
        <div><div class="section-kicker light">下一步</div><h2 id="contact-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '先建立研究受众，再销售报告。' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'description', $block ?? null, '第一目标是可信度：持续发布有用情报，建立信任，然后将最强的研究转化为高级出版物。' ) ) ); ?></p></div>
        <div class="media-actions"><a class="btn btn-light" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'primary_action', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13575#newsletter', 'title' => '订阅情报', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'primary_action', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13575#newsletter', 'title' => '订阅情报', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'secondary_action', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13605', 'title' => '媒体中心', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'secondary_action', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13605', 'title' => '媒体中心', 'target' => '' ) ) ) ); ?></a></div>
      </div>
    </section>
