<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="analysis" aria-labelledby="analysis-title"><div class="container"><div class="section-head"><div><div class="section-kicker">What We Analyze</div><h2 id="analysis-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Four decision-critical areas.' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'The platform focuses on the questions that determine whether a food-trade opportunity can be executed profitably and compliantly.' ) ) ); ?></p></div></div><div class="analysis-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="expertise-card"><span><?php echo esc_html( (string) ( $qsoft_row['number'] ?? '' ) ); ?></span><h3><?php echo esc_html( (string) ( $qsoft_row['heading'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p><a class="card-link" href="<?php echo \Qwerty\Soft\Support\DesignField::url( $qsoft_row['link'] ?? '' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( $qsoft_row['link'] ?? '' ) ); ?></a></article><?php endforeach; ?></div></div></section>
