<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="principles" aria-labelledby="principles-title"><div class="container"><div class="section-kicker">Editorial Position</div><h2 id="principles-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Evidence first, marketing second.' ) ) ); ?></h2><div class="principles-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="principle"><span><?php echo esc_html( (string) ( $qsoft_row['number'] ?? '' ) ); ?></span><h3><?php echo esc_html( (string) ( $qsoft_row['principle'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div></div></section>
