<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section about-preview" aria-labelledby="about-preview-title"><div class="container about-preview-grid"><div><picture><source srcset="../assets/photos/robert-khoubian-about.webp" type="image/webp"></source><img src="<?php echo esc_url( \Qwerty\Soft\Support\DesignField::image_url( \Qwerty\Soft\Support\DesignField::value( 'portrait', $block ?? null, 'http://localhost/winonweb-them/wp-content/uploads/2026/08/robert-khoubian-about-1.jpg' ) ) ); ?>" alt="<?php echo esc_attr( \Qwerty\Soft\Support\DesignField::image_alt( \Qwerty\Soft\Support\DesignField::value( 'portrait', $block ?? null, 'http://localhost/winonweb-them/wp-content/uploads/2026/08/robert-khoubian-about-1.jpg' ) ) ); ?>" width="900" height="1125"></picture></div><div><div class="section-kicker light">关于 Robert</div><h2 id="about-preview-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '商业执行、监管知识与市场情报。' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'bio', $block ?? null, 'Robert Khoubian 是国际食品贸易专业人士和企业家，专注于中国—欧亚食品贸易、冷冻食品供应链和市场准入。自 2004 年以来，他一直活跃于全球食品市场，将商业执行经验、监管知识和实战型市场情报结合起来。' ) ) ); ?></p><a class="btn btn-primary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'read_more', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13577', 'title' => '阅读简介', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'read_more', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13577', 'title' => '阅读简介', 'target' => '' ) ) ) ); ?></a></div></div></section>
