<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section"><div class="container"><p class="section-kicker"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'kicker', $block ?? null, 'Стратегия продукта' ) ) ); ?></p><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Не чат-бот. Масштабируемый интеллектуальный слой.' ) ) ); ?></h2><p class="intro"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'Robert AI должен стать интерфейсом между пользователями и накопленными знаниями Роберта Хубияна: отчетами, методологией, видео, чеклистами, опытом Aquaprole Market Intelligence и проверенными trade frameworks.' ) ) ); ?></p></div></section>
