<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section featured-publications" aria-labelledby="featured-title"><div class="container"><div class="section-head"><div><div class="section-kicker">Featured Publications</div><h2 id="featured-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Evidence before opinion.' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'Public intelligence briefs, customs-based market analysis and premium reports designed for operators, institutions and media.' ) ) ); ?></p></div><a class="text-link" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'all_reports_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13580', 'title' => 'Browse all reports →', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'all_reports_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13580', 'title' => 'Browse all reports →', 'target' => '' ) ) ) ); ?></a></div>
      <div class="reports-grid compact-reports">
        <?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="report-card"><div class="report-cover cover-eurasia"><span><?php echo esc_html( (string) ( $qsoft_row['label'] ?? '' ) ); ?></span><strong><?php echo esc_html( (string) ( $qsoft_row['label_2'] ?? '' ) ); ?></strong><small><?php echo esc_html( (string) ( $qsoft_row['label_3'] ?? '' ) ); ?></small></div><div class="report-body"><div class="report-meta"><span><?php echo esc_html( (string) ( $qsoft_row['label_4'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['label_5'] ?? '' ) ); ?></span></div><h3><?php echo esc_html( (string) ( $qsoft_row['subheading'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['text'] ?? '' ) ); ?></p><div class="report-actions"><a class="btn btn-outline" href="<?php echo \Qwerty\Soft\Support\DesignField::url( $qsoft_row['btn'] ?? '' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( $qsoft_row['btn'] ?? '' ) ); ?></a></div></div></article><?php endforeach; ?>
        
        
      </div>
    </div></section>
