<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="latest-video"><div class="container video-intelligence-grid"><div class="video-player-card"><span class="video-duration"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'duration', $block ?? null, '4:30' ) ) ); ?></span><span class="video-play"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'play_icon', $block ?? null, '▶' ) ) ); ?></span><div class="video-player-copy"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'eyebrow', $block ?? null, '最新简报' ) ) ); ?></span><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '如何阅读一份基于海关数据的市场报告' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'summary', $block ?? null, '简明说明HS编码、数据覆盖、排名限制以及数字背后的商业含义。' ) ) ); ?></p></div></div><aside class="video-learn-card"><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'takeaways_heading', $block ?? null, '您将了解' ) ) ); ?></h3><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><?php echo esc_html( (string) ( $qsoft_row['takeaway'] ?? '' ) ); ?></li><?php endforeach; ?></ul><p class="video-disclosure"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'ai_disclosure', $block ?? null, '本视频采用 Robert Khoubian 经批准的数字分身和声音克隆进行AI辅助呈现。脚本、分析和最终发布均由 Robert Khoubian 审核批准。' ) ) ); ?></p></aside></div></section>
