<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft footprint" aria-labelledby="footprint-title"><div class="container footprint-grid"><div class="footprint-copy"><div class="section-kicker">Глобальная география</div><h2 id="footprint-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Рынки, подтвержденные практическим опытом.' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'Работа Роберта охватывает рынки поставщиков, рынки назначения, государственные торговые миссии и проекты вывода продуктов в регулируемые розничные каналы. Фокус — не теория, а практическое исполнение в food trade corridors.' ) ) ); ?></p></div><div class="map-card"><div class="region-list"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><div class="region-row"><strong><?php echo esc_html( (string) ( $qsoft_row['region'] ?? '' ) ); ?></strong><div class="country-chips"><span><?php echo esc_html( (string) ( $qsoft_row['countries'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['more_countries'] ?? '' ) ); ?></span></div></div><?php endforeach; ?></div></div></div></section>
