<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="licenses" aria-labelledby="license-title">
      <div class="container"><div class="section-head"><div><div class="section-kicker">Licensing</div><h2 id="license-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '许可结构' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '报告从第一天起就应以清晰的使用权出售。这有助于保护知识产权，并减少企业买家的理解风险。' ) ) ); ?></p></div></div><div class="license-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="license-card"><h3><?php echo esc_html( (string) ( $qsoft_row['license_name'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['license_description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div></div>
    </section>
