<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="hero section-dark hero-product" aria-labelledby="hero-title">
      <div class="hero-bg" aria-hidden="true"><svg class="route-map" viewbox="0 0 1440 760" preserveaspectratio="none"><defs><lineargradient id="route" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#d5b46a" stop-opacity="0.10"></stop><stop offset="0.45" stop-color="#6aa1d5" stop-opacity="0.22"></stop><stop offset="1" stop-color="#d5b46a" stop-opacity="0.10"></stop></lineargradient></defs><path d="M-30,575 C130,430 280,510 430,400 C610,270 765,330 920,215 C1080,95 1240,145 1470,45" fill="none" stroke="url(#route)" stroke-width="2"></path><path d="M-20,650 C175,520 320,600 505,475 C670,362 845,410 1045,295 C1190,210 1280,240 1460,178" fill="none" stroke="url(#route)" stroke-width="1" opacity=".85"></path><circle cx="330" cy="456" r="5" fill="#d5b46a" opacity=".8"></circle><circle cx="716" cy="338" r="4" fill="#d5b46a" opacity=".75"></circle><circle cx="1040" cy="294" r="5" fill="#d5b46a" opacity=".8"></circle></svg></div>
      <div class="container hero-grid">
        <div class="hero-copy">
          <p class="eyebrow"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'eyebrow', $block ?? null, 'Evidence-led intelligence for global food trade' ) ) ); ?></p>
          <h1 id="hero-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'China–Eurasia Food Trade Intelligence' ) ) ); ?></h1>
          <p class="hero-lede"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'Research, customs analysis and market-access insight built on more than 20 years of operating experience.' ) ) ); ?></p>
          <p class="hero-byline"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'byline', $block ?? null, 'Led by Robert Khoubian, CEO of Aquaprole Group.' ) ) ); ?></p>
          <div class="hero-actions"><a class="btn btn-primary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'primary_cta', $block ?? null, array( 'url' => '#latest-intelligence', 'title' => 'Explore Latest Intelligence', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'primary_cta', $block ?? null, array( 'url' => '#latest-intelligence', 'title' => 'Explore Latest Intelligence', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'secondary_cta', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13580', 'title' => 'View Reports', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'secondary_cta', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13580', 'title' => 'View Reports', 'target' => '' ) ) ) ); ?></a></div>
        </div>
        <aside class="hero-visual" aria-label="Robert Khoubian portrait and professional positioning">
          <div class="hero-photo-frame"><picture><source srcset="../assets/photos/robert-khoubian-hero.webp" type="image/webp"></source><img src="<?php echo esc_url( \Qwerty\Soft\Support\DesignField::image_url( \Qwerty\Soft\Support\DesignField::value( 'portrait', $block ?? null, 'http://localhost/winonweb-them/wp-content/uploads/2026/08/robert-khoubian-hero-1.jpg' ) ) ); ?>" alt="<?php echo esc_attr( \Qwerty\Soft\Support\DesignField::image_alt( \Qwerty\Soft\Support\DesignField::value( 'portrait', $block ?? null, 'http://localhost/winonweb-them/wp-content/uploads/2026/08/robert-khoubian-hero-1.jpg' ) ) ); ?>" width="900" height="1125"></picture><div class="photo-caption"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'portrait_name', $block ?? null, 'Robert Khoubian' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'portrait_role', $block ?? null, 'International Food Trade Executive' ) ) ); ?></strong><small><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'portrait_role_secondary', $block ?? null, 'Market Intelligence Publisher' ) ) ); ?></small></div></div>
          <div class="hero-panel compact"><div class="panel-header"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'focus_label', $block ?? null, 'Core Focus' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'focus_areas', $block ?? null, 'China • Eurasia • Frozen Food' ) ) ); ?></strong></div><div class="mini-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><div><span><?php echo esc_html( (string) ( $qsoft_row['stat_label'] ?? '' ) ); ?></span><strong><?php echo esc_html( (string) ( $qsoft_row['stat_value'] ?? '' ) ); ?></strong></div><?php endforeach; ?></div></div>
        </aside>
      </div>
    </section>
