<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section"><div class="container scorecard-layout"><div><div class="section-kicker">示例评分卡</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '展示样式示例——并非已发布市场排名' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '以下评分仅用于页面设计演示，不得作为当前市场结论引用。' ) ) ); ?></p><div class="legal-note"><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'notice_heading', $block ?? null, '名称与方法说明' ) ) ); ?></strong><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'notice_text', $block ?? null, 'Robert Khoubian Market Intelligence Index™、RKMII™ 及相关评分卡设计作为专有品牌和方法标识使用。™ 表示对商标权益的主张，并不代表已获得商标注册。' ) ) ); ?></p></div></div><div class="scorecard-demo"><div class="scorecard-top"><div><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'overall_score_label', $block ?? null, '示例综合评分' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'overall_score', $block ?? null, '82' ) ) ); ?></strong></div><b><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'status', $block ?? null, '状态：仅供演示' ) ) ); ?></b></div></div></div></section>
