<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="executive-summary">
    <div class="container report-detail-grid">
      <div class="proof-copy"><div class="section-kicker">Executive Summary</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Where oat opportunities look strongest.' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'summary', $block ?? null, 'The source report indicates that oat product activity is not evenly distributed. Mexico and Brazil are the largest selected markets by combined proxy volume and product-launch activity, while Japan is the largest selected APAC market. The Philippines and South Korea appear more targeted, with useful innovation signals and Canadian product presence.' ) ) ); ?></p></div>
      <div class="proof-panel"><ul class="report-summary-list">
        <?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['finding'] ?? '' ) ); ?></span></li><?php endforeach; ?>
        
        
        
        
      </ul></div>
    </div>
  </section>
