<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="page-hero" aria-labelledby="about-title"><div class="container page-hero-grid"><div><div class="section-kicker">专业简介</div><h1 id="about-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '关于 Robert Khoubian' ) ) ); ?></h1><p class="lead"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lead', $block ?? null, '国际食品贸易专业人士、企业家和市场情报发布者，专注中国—欧亚食品贸易、冷冻食品供应链和跨境市场准入。' ) ) ); ?></p></div><aside class="about-card" aria-label="简要信息"><picture><source srcset="http://localhost/winonweb-them/wp-content/uploads/2026/08/robert-khoubian-about-1.jpg" type="image/webp"></source><img src="<?php echo esc_url( \Qwerty\Soft\Support\DesignField::image_url( \Qwerty\Soft\Support\DesignField::value( 'image', $block ?? null, 'http://localhost/winonweb-them/wp-content/uploads/2026/08/robert-khoubian-about-1.jpg' ) ) ); ?>" alt="<?php echo esc_attr( \Qwerty\Soft\Support\DesignField::image_alt( \Qwerty\Soft\Support\DesignField::value( 'image', $block ?? null, 'http://localhost/winonweb-them/wp-content/uploads/2026/08/robert-khoubian-about-1.jpg' ) ) ); ?>" width="900" height="1125"></picture><div class="about-facts"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><div class="about-fact"><span><?php echo esc_html( (string) ( $qsoft_row['fact_label'] ?? '' ) ); ?></span><strong><?php echo esc_html( (string) ( $qsoft_row['fact_value'] ?? '' ) ); ?></strong></div><?php endforeach; ?></div></aside></div></section>
