<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="facts" aria-labelledby="facts-title">
      <div class="container proof-grid">
        <div class="proof-copy"><div class="section-kicker">Evidence-Based Profile</div><h2 id="facts-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '媒体可用的专业信息' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '以下内容适合作为专业简介要点。需要证明文件的高影响力声明将单独保存在项目 evidence register 中，并应在正式引用前完成验证。' ) ) ); ?></p></div>
        <div class="proof-panel"><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['fact'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul></div>
      </div>
    </section>
