<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="framework"><div class="container"><div class="section-head"><div><div class="section-kicker">指数框架</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '指数衡量什么' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '每一项公开评分均应基于有记录的输入数据、标准化子评分及注明日期的方法说明。不同指数类别可采用不同权重，但公开结果必须披露适用版本与数据期间。' ) ) ); ?></p></div></div><div class="index-dimensions"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="index-dimension"><div class="index-dimension-head"><h3><?php echo esc_html( (string) ( $qsoft_row['dimension_name'] ?? '' ) ); ?></h3><span><?php echo esc_html( (string) ( $qsoft_row['weight'] ?? '' ) ); ?></span></div><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div></div></section>
