<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="intelligence" aria-labelledby="topics-title"><div class="container"><div class="section-head"><div><div class="section-kicker">重点主题</div><h2 id="topics-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '核心分析领域。' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, '这些主题将成为未来文章、报告、视频和付费市场情报产品的基础。' ) ) ); ?></p></div></div><div class="topic-grid" id="topics"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="topic-card"><div class="topic-visual visual-1"></div><p class="tag"><?php echo esc_html( (string) ( $qsoft_row['category'] ?? '' ) ); ?></p><h3><?php echo esc_html( (string) ( $qsoft_row['heading'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p><a href="<?php echo \Qwerty\Soft\Support\DesignField::url( $qsoft_row['subscribe_link'] ?? '' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( $qsoft_row['subscribe_link'] ?? '' ) ); ?></a></article><?php endforeach; ?></div></div></section>
