<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="hero"><div class="container hero-grid"><div><p class="eyebrow"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'eyebrow', $block ?? null, 'AI 辅助贸易智能' ) ) ); ?></p><h1><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Robert AI' ) ) ); ?></h1><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'subheading', $block ?? null, '基于 Robert Khoubian 方法论的国际商务与食品贸易智能助手。' ) ) ); ?></h2><p class="lede"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, '一个受控的 AI 咨询界面，帮助专业用户理解全球食品贸易、中国—欧亚供应链、市场准入、海关数据、贸易风险和报告分析。' ) ) ); ?></p><div class="btns"><a class="btn primary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'waitlist_link', $block ?? null, array( 'url' => '#waitlist', 'title' => '加入候补名单', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'waitlist_link', $block ?? null, array( 'url' => '#waitlist', 'title' => '加入候补名单', 'target' => '' ) ) ) ); ?></a><a class="btn secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'knowledge_link', $block ?? null, array( 'url' => '#knowledge', 'title' => '查看知识范围', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'knowledge_link', $block ?? null, array( 'url' => '#knowledge', 'title' => '查看知识范围', 'target' => '' ) ) ) ); ?></a></div></div>
<aside class="ai-console"><div class="chat-head"><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'console_title', $block ?? null, 'Robert AI 咨询控制台' ) ) ); ?></strong><span class="status"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'console_status', $block ?? null, '● 原型模式' ) ) ); ?></span></div><div class="msg user">在给予格鲁吉亚禽肉进口商账期之前，应如何评估客户风险？</div><div class="msg ai">应从买方验证、进口历史、冷链能力、付款行为、信用保险、文件准备和当地监管风险开始。高金额风险需要人工复核。</div><div class="chips"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><span class="chip"><?php echo esc_html( (string) ( $qsoft_row['topic'] ?? '' ) ); ?></span><?php endforeach; ?></div><div class="mock-input"><input data-demo-input placeholder="Ask Robert AI..."><button>Ask</button></div></aside>
</div></section>
