<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="methodology" aria-labelledby="methodology-title">
      <div class="container proof-grid">
        <div class="proof-copy"><div class="section-kicker">研究方法</div><h2 id="methodology-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '基于实际经营经验的研究方法' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'description', $block ?? null, '平台应建立在严谨的研究流程之上：实际市场知识、可获得的官方或可靠数据、监管跟踪、已记录的经验，以及事实与观点的明确区分。高影响力商业声明在证明材料准备完成前保留在 evidence register 中。' ) ) ); ?></p></div>
        <div class="proof-panel methodology-panel"><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['principle'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul></div>
      </div>
    </section>
