<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="media-strip"><div class="container media-strip-grid"><div><div class="section-kicker light">RKMII™</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Строить индекс аккуратно. Публиковать убедительно.' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'description', $block ?? null, 'Первый публичный индекс должен охватывать один продукт, один торговый коридор и полностью документированный знаменатель. Качество доказательств важнее количества рейтингов.' ) ) ); ?></p></div><div class="media-actions"><a class="btn btn-light" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'primary_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13600', 'title' => 'Перейти к исследованиям', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'primary_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13600', 'title' => 'Перейти к исследованиям', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'secondary_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13596', 'title' => 'Reports', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'secondary_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13596', 'title' => 'Reports', 'target' => '' ) ) ) ); ?></a></div></div></section>
