<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="profile" aria-labelledby="profile-title">
      <div class="container media-layout">
        <div class="content-block feature-block">
          <div class="section-kicker">Media-Ready Profile</div>
          <h2 id="profile-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Who is Robert Khoubian?' ) ) ); ?></h2>
          <div class="two-col media-bio">
            <article><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'short_bio_heading', $block ?? null, 'Short biography' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'short_bio', $block ?? null, 'Robert Khoubian is an international food trade professional, entrepreneur and market intelligence publisher specializing in China–Eurasia food trade, frozen food supply chains and cross-border market access. Since 2004, he has worked across China, Russia and CIS markets, North America, Southeast Asia and the European Union.' ) ) ); ?></p></article>
            <article><h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'extended_bio_heading', $block ?? null, 'Extended biography' ) ) ); ?></h3><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'extended_bio', $block ?? null, 'Robert’s work combines commercial execution, regulatory knowledge and practical market intelligence. His experience includes international food trading, customs and veterinary requirements, Canadian government trade missions, retail product adaptation, cold-chain logistics and the development of Aquaprole Group across Canada, the United States, Singapore, China and Hong Kong.' ) ) ); ?></p></article>
          </div>
        </div>
        <aside class="content-block quick-panel">
          <h3><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'formats_heading', $block ?? null, 'Preferred formats' ) ) ); ?></h3>
          <div class="country-chips media-chips"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><span><?php echo esc_html( (string) ( $qsoft_row['format'] ?? '' ) ); ?></span><?php endforeach; ?></div>
        </aside>
      </div>
    </section>
