<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="interpretation"><div class="container"><div class="section-head"><div><div class="section-kicker">0–100</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Как читать индекс' ) ) ); ?></h2></div></div><div class="index-bands"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><div class="index-band"><strong><?php echo esc_html( (string) ( $qsoft_row['score_range'] ?? '' ) ); ?></strong><div><h3><?php echo esc_html( (string) ( $qsoft_row['band_name'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></div></div><?php endforeach; ?></div></div></section>
