<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="admin-upload" aria-labelledby="admin-title">
      <div class="container proof-grid"><div class="proof-copy"><div class="section-kicker">Admin Panel Ready</div><h2 id="admin-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Admin upload fields' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'Когда ты подготовишь каждый отчет, admin panel должна позволять загружать или редактировать эти поля без участия developer.' ) ) ); ?></p></div><div class="proof-panel admin-list"><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['upload_field'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul></div></div>
    </section>
