<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section youtube-band"><div class="container youtube-band-grid"><div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '在 YouTube 获取最新视频简报' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, '观看最新市场情报视频、报告解读和短视频更新。' ) ) ); ?></p></div><a class="btn btn-primary youtube-link" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'channel_link', $block ?? null, array( 'url' => '#', 'title' => '访问 YouTube 频道', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>" aria-disabled="true" data-cms-field="youtube_channel_url"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'channel_link', $block ?? null, array( 'url' => '#', 'title' => '访问 YouTube 频道', 'target' => '' ) ) ) ); ?></a></div></section>
