<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="expertise" aria-labelledby="expertise-title"><div class="container"><div class="section-head"><div><div class="section-kicker">Практическая аналитика</div><h2 id="expertise-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Для решений в международной торговле продуктами питания.' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'Платформа сфокусирована на информации, которая нужна операторам перед выходом на рынок, выбором поставщиков, расчетом цены и управлением трансграничными рисками.' ) ) ); ?></p></div></div><div class="card-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="expertise-card"><span><?php echo esc_html( (string) ( $qsoft_row['number'] ?? '' ) ); ?></span><h3><?php echo esc_html( (string) ( $qsoft_row['heading'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div></div></section>
