<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft"><div class="container"><div class="section-head"><div><div class="section-kicker">Библиотека видео</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Каждое видео связывает отчет с понятным объяснением доказательств, ограничений и бизнес-выводов.' ) ) ); ?></h2></div></div><div class="video-grid"><?php foreach ( \Qwerty\Soft\Support\DesignListing::rows( \Qwerty\Soft\Support\DesignField::value( 'source', $block ?? null ), (int) \Qwerty\Soft\Support\DesignField::value( 'limit', $block ?? null ), array( 'play_icon' => 'text', 'duration' => 'text', 'topic' => 'text', 'watch_time' => 'text', 'title' => 'text', 'description' => 'textarea', 'watch_link' => 'link' ), 'qs_video' ) as $qsoft_row ) : ?><article class="video-card"><div class="video-thumb"><span class="video-play" aria-hidden="true"><?php echo esc_html( (string) ( $qsoft_row['play_icon'] ?? '' ) ); ?></span><span class="video-duration"><?php echo esc_html( (string) ( $qsoft_row['duration'] ?? '' ) ); ?></span></div><div class="video-card-body"><div class="video-meta"><span><?php echo esc_html( (string) ( $qsoft_row['topic'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['watch_time'] ?? '' ) ); ?></span></div><h3><?php echo esc_html( (string) ( $qsoft_row['title'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p><a class="text-link" href="<?php echo \Qwerty\Soft\Support\DesignField::url( $qsoft_row['watch_link'] ?? '' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>" aria-disabled="true"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( $qsoft_row['watch_link'] ?? '' ) ); ?></a></div></article><?php endforeach; ?></div></div></section>
