<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section dark"><div class="container"><p class="section-kicker"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'kicker', $block ?? null, 'Governance' ) ) ); ?></p><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Контроль, доверие и защита от неверных claims' ) ) ); ?></h2><div class="grid four"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="card"><h3><?php echo esc_html( (string) ( $qsoft_row['heading'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div><p class="warning" style="margin-top:24px"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'disclaimer', $block ?? null, 'Robert AI — AI-assisted trade intelligence system. Он не заменяет legal, tax, customs, financial, veterinary или sanctions advice. При расхождении перевода контролирующей версией должны оставаться утвержденные исходные материалы.' ) ) ); ?></p></div></section>
