<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="media-hero section-dark" aria-labelledby="media-title">
      <div class="hero-bg" aria-hidden="true"><svg class="route-map" viewbox="0 0 1440 760" preserveaspectratio="none"><defs><lineargradient id="route" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#d5b46a" stop-opacity="0.10"></stop><stop offset="0.45" stop-color="#6aa1d5" stop-opacity="0.22"></stop><stop offset="1" stop-color="#d5b46a" stop-opacity="0.10"></stop></lineargradient></defs><path d="M-30,575 C130,430 280,510 430,400 C610,270 765,330 920,215 C1080,95 1240,145 1470,45" fill="none" stroke="url(#route)" stroke-width="2"></path><path d="M-20,650 C175,520 320,600 505,475 C670,362 845,410 1045,295 C1190,210 1280,240 1460,178" fill="none" stroke="url(#route)" stroke-width="1" opacity=".85"></path><circle cx="330" cy="456" r="5" fill="#d5b46a" opacity=".8"></circle><circle cx="716" cy="338" r="4" fill="#d5b46a" opacity=".75"></circle><circle cx="1040" cy="294" r="5" fill="#d5b46a" opacity=".8"></circle></svg></div>
      <div class="container media-hero-grid">
        <div class="media-hero-copy">
          <p class="eyebrow"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'eyebrow', $block ?? null, 'Media & Press Center' ) ) ); ?></p>
          <h1 id="media-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Expert commentary on global food trade.' ) ) ); ?></h1>
          <p class="hero-lede"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'hero_lede', $block ?? null, 'Resources for journalists, conference organizers, trade associations and industry partners seeking informed commentary on China–Eurasia food trade, frozen food supply chains, market access and international trade execution.' ) ) ); ?></p>
          <div class="hero-actions"><a class="btn btn-primary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'primary_link', $block ?? null, array( 'url' => '#topics', 'title' => 'Interview Topics', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'primary_link', $block ?? null, array( 'url' => '#topics', 'title' => 'Interview Topics', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'secondary_link', $block ?? null, array( 'url' => '#contact', 'title' => 'Media Contact', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'secondary_link', $block ?? null, array( 'url' => '#contact', 'title' => 'Media Contact', 'target' => '' ) ) ) ); ?></a></div>
        </div>
        <aside class="press-card">
          <picture><source srcset="http://localhost/winonweb-them/wp-content/uploads/2026/08/robert-khoubian-hero-1.jpg" type="image/webp"></source><img src="<?php echo esc_url( \Qwerty\Soft\Support\DesignField::image_url( \Qwerty\Soft\Support\DesignField::value( 'portrait', $block ?? null, 'http://localhost/winonweb-them/wp-content/uploads/2026/08/robert-khoubian-hero-1.jpg' ) ) ); ?>" alt="<?php echo esc_attr( \Qwerty\Soft\Support\DesignField::image_alt( \Qwerty\Soft\Support\DesignField::value( 'portrait', $block ?? null, 'http://localhost/winonweb-them/wp-content/uploads/2026/08/robert-khoubian-hero-1.jpg' ) ) ); ?>" width="900" height="1125"></picture>
          <div class="press-card-body"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'profile_label', $block ?? null, 'Media Profile' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'person_name', $block ?? null, 'Robert Khoubian' ) ) ); ?></strong><small><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'expertise', $block ?? null, 'China • Eurasia • Frozen Food Supply Chains' ) ) ); ?></small></div>
        </aside>
      </div>
      <div class="intelligence-strip" role="list" aria-label="Media formats"><span role="listitem"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'formats_label', $block ?? null, 'Media Formats' ) ) ); ?></span></div>
    </section>
