<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="discipline" aria-labelledby="discipline-title">
      <div class="container"><div class="method-note"><div class="section-kicker">Evidence &amp; Compliance</div><h2 id="discipline-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '发布纪律' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'body', $block ?? null, '高价值声明、排名、零售覆盖、会员资格和政府相关参与，应在进入付费报告、媒体推广或 Wikipedia 相关材料前，与内部 evidence register 对应并验证。' ) ) ); ?></p></div></div>
    </section>
