<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="media-strip"><div class="container media-strip-grid"><div><div class="section-kicker light">RKMII™</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '谨慎建立指数，可信地发布。' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'body_text', $block ?? null, '首个公开指数应聚焦一个产品、一个贸易走廊及一个可完整记录的市场分母。证据质量比发布排名的数量更重要。' ) ) ); ?></p></div><div class="media-actions"><a class="btn btn-light" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'research_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13610', 'title' => '浏览研究', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'research_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13610', 'title' => '浏览研究', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'reports_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13606', 'title' => 'Reports', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'reports_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13606', 'title' => 'Reports', 'target' => '' ) ) ) ); ?></a></div></div></section>
