<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="customs-reports" aria-labelledby="customs-title">
      <div class="container"><div class="section-head"><div><div class="section-kicker">已载入来源报告</div><h2 id="customs-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '海关数据报告已作为初始资料载入。' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '这些报告已作为后台验证资料加入原型。公开样本和付费版本应在发布前完成脱敏和审批。' ) ) ); ?></p></div></div><div class="license-grid"><?php foreach ( \Qwerty\Soft\Support\DesignListing::rows( \Qwerty\Soft\Support\DesignField::value( 'source', $block ?? null ), (int) \Qwerty\Soft\Support\DesignField::value( 'limit', $block ?? null ), array( 'report_title' => 'text', 'summary' => 'textarea', 'report_link' => 'link' ), '' ) as $qsoft_row ) : ?><article class="license-card"><h3><?php echo esc_html( (string) ( $qsoft_row['report_title'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['summary'] ?? '' ) ); ?></p><a class="text-link" href="<?php echo \Qwerty\Soft\Support\DesignField::url( $qsoft_row['report_link'] ?? '' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( $qsoft_row['report_link'] ?? '' ) ); ?></a></article><?php endforeach; ?></div></div>
    </section>
