<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft footprint" aria-labelledby="footprint-title"><div class="container footprint-grid"><div class="footprint-copy"><div class="section-kicker">全球足迹</div><h2 id="footprint-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '来自实战经验的市场覆盖。' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'Robert 的工作覆盖供应市场、目的地市场、政府相关贸易代表团以及受监管零售渠道的产品导入项目。重点不是理论，而是食品贸易走廊中的实际执行。' ) ) ); ?></p></div><div class="map-card"><div class="region-list"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><div class="region-row"><strong><?php echo esc_html( (string) ( $qsoft_row['region'] ?? '' ) ); ?></strong><div class="country-chips"><span><?php echo esc_html( (string) ( $qsoft_row['country'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['country_2'] ?? '' ) ); ?></span></div></div><?php endforeach; ?></div></div></div></section>
