<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="checkout-flow" aria-labelledby="flow-title">
      <div class="container"><div class="section-head"><div><div class="section-kicker">Commerce System</div><h2 id="flow-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, '支付与交付流程' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, '生产版 CMS 应将报告与结账和受保护的数字交付连接起来。静态原型展示结构；上线版本应自动处理支付和文件交付。' ) ) ); ?></p></div></div><div class="flow-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="flow-step"><span><?php echo esc_html( (string) ( $qsoft_row['step_number'] ?? '' ) ); ?></span><h3><?php echo esc_html( (string) ( $qsoft_row['step_heading'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['step_description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div></div>
    </section>
