<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section proof" id="proof" aria-labelledby="proof-title"><div class="container proof-grid"><div class="proof-copy"><div class="section-kicker">从研究到执行</div><h2 id="proof-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Aquaprole 体现真实运营经验。' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'description', $block ?? null, 'Robert 的市场情报建立在实际国际贸易经验之上。作为 Aquaprole Group CEO，他整合了加拿大、美国、新加坡、中国和香港的食品贸易业务，涉及采购、物流、市场准入、冷链运营和自有品牌产品开发。' ) ) ); ?></p><div class="section-actions"><a class="btn btn-outline" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'profile_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13577', 'title' => '阅读简介', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'profile_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13577', 'title' => '阅读简介', 'target' => '' ) ) ) ); ?></a></div></div><div class="proof-panel"><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['proof_point'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul></div></div></section>
