<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft" id="publishing" aria-labelledby="publishing-title">
      <div class="container">
        <div class="section-head"><div><div class="section-kicker">План публикаций</div><h2 id="publishing-title"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Как будут публиковаться исследования' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'Платформа должна сочетать бесплатную и платную аналитику. Бесплатный контент строит доверие и поисковую видимость. Платные отчеты становятся коммерческим продуктом после накопления глубокой research library.' ) ) ); ?></p></div></div>
        <div class="publication-grid"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="project-card"><h3><?php echo esc_html( (string) ( $qsoft_row['format_name'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div>
      </div>
    </section>
