<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="reports-hero section-dark">
    <div class="hero-bg" aria-hidden="true"></div>
    <div class="container reports-hero-grid">
      <div class="hero-copy">
        <p class="eyebrow"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'eyebrow', $block ?? null, 'Customs Data Report' ) ) ); ?></p>
        <h1><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'China-to-Kazakhstan Frozen Potato Exporter Ranking (HS 2004.10)' ) ) ); ?></h1>
        <p class="hero-lede"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'Position of Aquaprole among disclosed exporters, July 2025 – June 2026.' ) ) ); ?></p>
        <p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'availability_note', $block ?? null, 'These pages are designed as report-detail templates. The source DOCX files remain admin-only until redacted public samples and approved commercial versions are prepared.' ) ) ); ?></p>
        <div class="hero-actions"><a class="btn btn-primary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'back_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13580', 'title' => 'Return to Reports', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'back_link', $block ?? null, array( 'url' => 'http://localhost/winonweb-them/?page_id=13580', 'title' => 'Return to Reports', 'target' => '' ) ) ) ); ?></a><a class="btn btn-secondary" href="<?php echo \Qwerty\Soft\Support\DesignField::url( \Qwerty\Soft\Support\DesignField::value( 'methodology_link', $block ?? null, array( 'url' => '#methodology', 'title' => 'Methodology discipline', 'target' => '' ) ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped by url(), which leaves a relative link relative. ?>"><?php echo esc_html( \Qwerty\Soft\Support\DesignField::link_text( \Qwerty\Soft\Support\DesignField::value( 'methodology_link', $block ?? null, array( 'url' => '#methodology', 'title' => 'Methodology discipline', 'target' => '' ) ) ) ); ?></a></div>
      </div>
      <aside class="store-panel">
        <div class="store-panel-head"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'status_label', $block ?? null, 'Admin status' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'status_value', $block ?? null, 'Public sample pending' ) ) ); ?></strong></div>
        <div class="store-stats">
          <article class="store-stat"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'period_label', $block ?? null, 'Period' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'period_value', $block ?? null, 'July 2025 – June 2026.' ) ) ); ?></strong><small><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'period_note', $block ?? null, 'China-to-Kazakhstan Frozen Potato Exporter Ranking (HS 2004.10)' ) ) ); ?></small></article>
          <article class="store-stat"><span><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'rank_label', $block ?? null, 'Rank / position' ) ) ); ?></span><strong><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'rank_value', $block ?? null, '#11 of 20 disclosed exporters; approximately #10 if Kaida group is consolidated' ) ) ); ?></strong><small><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'rank_note', $block ?? null, 'Rank / position' ) ) ); ?></small></article>
        </div>
      </aside>
    </div>
  </section>
