<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section" id="framework"><div class="container"><div class="section-head"><div><div class="section-kicker">Структура индекса</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Что измеряет индекс' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'lede', $block ?? null, 'Каждый опубликованный балл должен основываться на документированных входных данных, стандартизированных субиндексах и датированной методологии. Вес показателей может отличаться по типу индекса, но публичный результат всегда должен раскрывать версию и период данных.' ) ) ); ?></p></div></div><div class="index-dimensions"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><article class="index-dimension"><div class="index-dimension-head"><h3><?php echo esc_html( (string) ( $qsoft_row['dimension'] ?? '' ) ); ?></h3><span><?php echo esc_html( (string) ( $qsoft_row['weight'] ?? '' ) ); ?></span></div><p><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></p></article><?php endforeach; ?></div></div></section>
