<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section soft"><div class="container proof-grid"><div class="proof-copy"><div class="section-kicker">Methodology &amp; Governance</div><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Evidence before score' ) ) ); ?></h2><p><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'intro', $block ?? null, 'RKMII™ is a proprietary analytical framework. The public value of the index depends on disciplined governance, not on the acronym alone. Scores should only be published when the underlying data scope, period, limitations and review status are documented.' ) ) ); ?></p></div><div class="proof-panel methodology-panel"><ul><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><li><span class="check"><?php echo esc_html( (string) ( $qsoft_row['check_mark'] ?? '' ) ); ?></span><span><?php echo esc_html( (string) ( $qsoft_row['principle'] ?? '' ) ); ?></span></li><?php endforeach; ?></ul></div></div></section>
