<?php
/**
 * A section of the design, rendered as the design wrote it.
 *
 * Generated by the importer. The markup below is the archive's own; the
 * only additions are the field values. Editing it by hand is allowed and
 * survives, because nothing regenerates a block that already exists.
 *
 * @package Qwerty\Soft
 * @license GPL-2.0-or-later
 */

declare( strict_types = 1 );

defined( 'ABSPATH' ) || exit;

?>
<section class="section dark"><div class="container"><p class="section-kicker"><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'section_kicker', $block ?? null, 'Roadmap' ) ) ); ?></p><h2><?php echo esc_html( (string) ( \Qwerty\Soft\Support\DesignField::value( 'heading', $block ?? null, 'Строим по контролируемым этапам' ) ) ); ?></h2><div class="flow"><?php foreach ( \Qwerty\Soft\Support\DesignField::rows( 'items', $block ?? null, false ) as $qsoft_row ) : ?><div><strong><?php echo esc_html( (string) ( $qsoft_row['phase'] ?? '' ) ); ?></strong><span><?php echo esc_html( (string) ( $qsoft_row['description'] ?? '' ) ); ?></span></div><?php endforeach; ?></div></div></section>
